# Exploratory data analysis - assignment.

## Introduction

The scripts in this repository create 6 separate plots as .png files saved to the current working directory.

Each plot is intended to answer a specific question relating to air quality data from the National Emissions Inventory (NEI), provided by the US Environmental Protection Agency (EPA). Read more at the [EPA National Emissions Inventory web site](http://www.epa.gov/ttn/chief/eiinformation.html).

The questions to answer, in brief, are as follows:

1. Have total emissions from PM2.5 decreased in the United States from 1999 to 2008? _(plot1.png)_
2. Have total emissions from PM2.5 decreased in the Baltimore City, Maryland from 1999 to 2008? _(plot2.png)_
3. Of the four types of sources indicated by the 𝚝𝚢𝚙𝚎 (point, nonpoint, onroad, nonroad) variable, which of these four sources have seen decreases or increases in emissions from 1999–2008 for Baltimore City? _(plot3.png)_
4. Across the United States, how have emissions from coal combustion-related sources changed from 1999–2008? _(plot4.png)_
5. How have emissions from motor vehicle sources changed from 1999–2008 in Baltimore City? _(plot5.png)_
6. Compare emissions from motor vehicle sources in Baltimore City with emissions from motor vehicle sources in Los Angeles County, California. Which city has seen greater changes over time in motor vehicle emissions? _(plot6.png)_

## Repository contents

- Individual scripts for creating each plot (plot1.R, plot2.R, etc), found in the root folder. 
- png files for each plot (plot1.png, plot2.png, etc), also found in the root folder.
- downloadData.R, a helper script which downloads and unzips the source data from the EPA if it is not in the user's current working directory.
- README.Rmd, this file.